add product finish

diff --git a/vendor/laravel/sail/bin/sail b/vendor/laravel/sail/bin/sail
--- a/vendor/laravel/sail/bin/sail
+++ b/vendor/laravel/sail/bin/sail
@@ -13,8 +13,8 @@ case "${UNAMEOUT}" in
 esac
 
 if [ "$MACHINE" == "UNKNOWN" ]; then
-    echo "Unsupported operating system [$(uname -s)]. Laravel Sail supports macOS, Linux, and Windows (WSL2)."
-    
+    echo "Unsupported operating system [$(uname -s)]. Laravel Sail supports macOS, Linux, and Windows (WSL2)." >&2
+
     exit 1
 fi
 
@@ -33,7 +33,7 @@ fi
 
 # Ensure that Docker is running...
 if ! docker info > /dev/null 2>&1; then
-    echo -e "${WHITE}Docker is not running.${NC}"
+    echo -e "${WHITE}Docker is not running.${NC}" >&2
 
     exit 1
 fi
@@ -41,7 +41,9 @@ fi
 # Determine if Sail is currently up...
 PSRESULT="$(docker-compose ps -q)"
 
-if docker-compose ps | grep 'Exit' &> /dev/null; then
+if docker-compose ps | grep 'Exit'; then
+    echo -e "${WHITE}Shutting down old Sail processes...${NC}" >&2
+
     docker-compose down > /dev/null 2>&1
 
     EXEC="no"
@@ -53,9 +55,9 @@ fi
 
 # Function that outputs Sail is not running...
 function sail_is_not_running {
-    echo -e "${WHITE}Sail is not running.${NC}"
-    echo ""
-    echo -e "${WHITE}You may Sail using the following commands:${NC} './vendor/bin/sail up' or './vendor/bin/sail up -d'"
+    echo -e "${WHITE}Sail is not running.${NC}" >&2
+    echo "" >&2
+    echo -e "${WHITE}You may Sail using the following commands:${NC} './vendor/bin/sail up' or './vendor/bin/sail up -d'" >&2
 
     exit 1
 }
@@ -133,6 +135,21 @@ if [ $# -gt 0 ]; then
             sail_is_not_running
         fi
 
+    # Proxy the "dusk:fails" command to the "php artisan dusk:fails" Artisan command...
+    elif [ "$1" == "dusk:fails" ]; then
+        shift 1
+
+        if [ "$EXEC" == "yes" ]; then
+            docker-compose exec \
+                -u sail \
+                -e "APP_URL=http://laravel.test" \
+                -e "DUSK_DRIVER_URL=http://selenium:4444/wd/hub" \
+                "$APP_SERVICE" \
+                php artisan dusk:fails "$@"
+        else
+            sail_is_not_running
+        fi
+
     # Initiate a Laravel Tinker session within the application container...
     elif [ "$1" == "tinker" ] ; then
         shift 1
@@ -185,6 +202,19 @@ if [ $# -gt 0 ]; then
             sail_is_not_running
         fi
 
+    # Proxy YARN commands to the "yarn" binary on the application container...
+    elif [ "$1" == "yarn" ]; then
+        shift 1
+
+        if [ "$EXEC" == "yes" ]; then
+            docker-compose exec \
+                -u sail \
+                "$APP_SERVICE" \
+                yarn "$@"
+        else
+            sail_is_not_running
+        fi
+
     # Initiate a MySQL CLI terminal session within the "mysql" container...
     elif [ "$1" == "mysql" ]; then
         shift 1
@@ -192,13 +222,25 @@ if [ $# -gt 0 ]; then
         if [ "$EXEC" == "yes" ]; then
             docker-compose exec \
                 mysql \
-                bash -c 'MYSQL_PWD=${MYSQL_ROOT_PASSWORD} mysql -u ${MYSQL_USER} ${MYSQL_DATABASE}'
+                bash -c 'MYSQL_PWD=${MYSQL_PASSWORD} mysql -u ${MYSQL_USER} ${MYSQL_DATABASE}'
+        else
+            sail_is_not_running
+        fi
+
+    # Initiate a PostgreSQL CLI terminal session within the "pgsql" container...
+    elif [ "$1" == "psql" ]; then
+        shift 1
+
+        if [ "$EXEC" == "yes" ]; then
+            docker-compose exec \
+                 pgsql \
+                 bash -c 'PGPASSWORD=${PGPASSWORD} psql -U ${POSTGRES_USER} ${POSTGRES_DB}'
         else
             sail_is_not_running
         fi
 
     # Initiate a Bash shell within the application container...
-    elif [ "$1" == "shell" ]; then
+    elif [ "$1" == "shell" ] || [ "$1" == "bash" ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
@@ -210,12 +252,24 @@ if [ $# -gt 0 ]; then
             sail_is_not_running
         fi
 
+    # Initiate a root user Bash shell within the application container...
+    elif [ "$1" == "root-shell" ] ; then
+        shift 1
+
+        if [ "$EXEC" == "yes" ]; then
+            docker-compose exec \
+                "$APP_SERVICE" \
+                bash
+        else
+            sail_is_not_running
+        fi
+
     # Share the site...
     elif [ "$1" == "share" ]; then
         shift 1
 
         if [ "$EXEC" == "yes" ]; then
-            docker run --init beyondcodegmbh/expose-server share http://host.docker.internal:"$APP_PORT" \
+            docker run --init beyondcodegmbh/expose-server:latest share http://host.docker.internal:"$APP_PORT" \
             --server-host=laravel-sail.site \
             --server-port=8080 \
             "$@"
